import type { Metadata } from "next";
import { AnimateOnScroll } from "@/components/landing/animate-on-scroll";

export const metadata: Metadata = {
  title: "Disclaimer",
  description:
    "Risk disclosure and regulatory notice for trading tools and indicators offered on this platform.",
};

const SECTIONS = [
  {
    title: "Risk Disclosure",
    paragraphs: [
      "Trading in financial markets involves substantial risk and may not be suitable for all investors. Our indicator is designed as a decision-support tool and should not be used as the sole basis for any trading or investment decision.",
      "Always combine the signals generated by this indicator with your own market analysis, trading knowledge, price action, risk management, and other technical or fundamental factors before entering a trade.",
      "Past performance does not guarantee future results. We do not guarantee profits or claim that losses can be avoided. You are solely responsible for your trading decisions and any financial outcomes.",
    ],
  },
  {
    title: "Regulatory Notice",
    paragraphs: [
      "We are not registered with the Securities and Exchange Board of India (SEBI) as an Investment Adviser (IA) or Research Analyst (RA). The information, tools, and indicators provided on this website are intended solely for educational and informational purposes and should not be construed as investment, financial, or trading advice.",
    ],
  },
  {
    title: "Acceptance",
    paragraphs: [
      "By using this website and our products, you acknowledge and accept these risks and agree that you are responsible for your own trading decisions.",
    ],
  },
];

export default function DisclaimerPage() {
  return (
    <div className="relative overflow-hidden">
      <div className="pointer-events-none absolute inset-0 landing-grid" />
      <div className="pointer-events-none absolute -top-40 left-1/2 h-[500px] w-[800px] -translate-x-1/2 rounded-full bg-primary/10 blur-3xl" />

      <div className="relative mx-auto max-w-3xl px-4 py-16 lg:py-24">
        <AnimateOnScroll>
          <div className="text-center">
            <h1 className="text-4xl font-bold tracking-tight text-foreground sm:text-5xl">
              Disclaimer
            </h1>
            <p className="mt-3 text-lg text-foreground-secondary">
              Please read this carefully before using our tools.
            </p>
          </div>
        </AnimateOnScroll>

        <div className="mt-12 space-y-10">
          {SECTIONS.map(({ title, paragraphs }, index) => (
            <AnimateOnScroll key={title} delay={100 + index * 80}>
              <section className="rounded-2xl border border-white/10 bg-surface/50 p-6 backdrop-blur-sm sm:p-8">
                <h2 className="text-xl font-semibold text-foreground">{title}</h2>
                <div className="mt-4 space-y-4 text-base leading-relaxed text-foreground-secondary">
                  {paragraphs.map((paragraph) => (
                    <p key={paragraph.slice(0, 40)}>{paragraph}</p>
                  ))}
                </div>
              </section>
            </AnimateOnScroll>
          ))}
        </div>
      </div>
    </div>
  );
}
